version: '3'

volumes:
  dbdata:

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_HOST_READ=database"
      - "DB_HOST_WRITE=database"
      - "DB_PORT=3306"

  web:
    build:
      context: ./
      dockerfile: ./.docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_DATABASE=marketplace"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=docker"
      - "MYSQL_PASSWORD=secret"
    ports:
    - "33060:3306"