version: 2
jobs:
  build:
      machine: true
      working_directory: ~/repo

      steps:
        - checkout

        # - restore_cache:
        #   keys:
        #     - composer-v1-{{ checksum "composer.lock" }}
        #     - composer-v1-

        - run:
            name: Docker
            command: |
              docker-compose up -d
              docker-compose ps
        - run: curl 127.0.0.1
        - run: curl 0.0.0.0
        # - save_cache:
        #     key: composer-v1-{{ checksum "composer.lock" }}
        #     paths:
        #       - vendor

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
