version: 2
jobs:
  build:
      machine: true
      working_directory: ~/repo

      steps:
        - checkout
        - lsb_release
        - run: echo "Hello World!"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
